### ISSUE TITLE
Guide lines moving event

### ISSUE THREAD

**Issue by azatkama** [Ju99ernaut/grapesjs-rulers#8]
Hi, @Ju99ernaut 

Could you add event like this https://github.com/azatkama/grapesjs-rulers/commit/5dec8df81fc4d1ccef6a5f8aa83a82e197fbb581#diff-7a1cf0079b9c38fef2bb394936faf595dc1034ae98865d304b2c48c3bb22ba9fR100
or callback maybe

I would like to magnetize lines to center of canvas

**Comment by Ju99ernaut** [comment]
I think any approach would be fine. Feel free to open a PR, you should also add some usage documentation to the README.
