### ISSUE TITLE
Issue with guide line and resizable components

### ISSUE THREAD

**Issue by azatkama** [Ju99ernaut/grapesjs-rulers#9]
There is issue with resizing of component after adding guide line
resizing works wrong after that
it is related to pointer events here https://github.com/azatkama/grapesjs-rulers/commit/e6abc7a4ddf958b1d34ab724edf03d60296fe7ba#diff-7a1cf0079b9c38fef2bb394936faf595dc1034ae98865d304b2c48c3bb22ba9fL561

**Comment by Ju99ernaut** [comment]
Feel free to open a PR for this, thanks!
